<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>997320bf-5295-4e60-98d3-8845742ad63f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GlamSpaces.Domain\GlamSpaces.Domain.csproj" />
    <ProjectReference Include="..\GlamSpaces.Infrastructure\GlamSpaces.Infrastructure.csproj" />
  </ItemGroup>

</Project>
